# Generated by Django 5.0.1 on 2024-01-07 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
